version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
  build:
    commands:
      - mvn clean package
  post_build:
    commands:
      - echo "hai"
artifacts:
  files:
    - target/*.war
